export dev=~/dev
export scripts=$dev/scripts
export env=$scripts/env
export PATH=$scripts/bin:/usr/local/bin:/usr/local/sbin:$PATH
export PATH=./node_modules/.bin:/usr/local/share/npm/bin:$PATH

export EDITOR='mate -w'
